name: Publish Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
            rogerscuall/gotalk:latest
            rogerscuall/gotalk:${{ github.ref_name }}
            rogerscuall/gotalk:${{ github.sha }}
